Added Rhino to the build procedure, and modified tostring-identity to pass under Rhino.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -22,10 +22,17 @@ fi
 rm -f .test-log
 for file in test/$1*.js; do
   echo $file
-  ${js:-d8} $debug caterwaul.js lib/unit.js $file
-  if [[ $? -eq 0 ]]; then echo pass $file >> .test-log
-  else                    echo fail $file >> .test-log
-                          echo -e "\033[1;31mfail\033[0;0m: $file"; fi
+  d8 $debug caterwaul.js lib/unit.js $file
+  if [[ $? -eq 0 ]]; then echo pass v8 $file >> .test-log
+  else                    echo fail v8 $file >> .test-log
+                          echo -e "\033[1;31mfail v8\033[0;0m: $file"; fi
+
+  cat $debug caterwaul.js lib/unit.js $file > tmp.js
+  rhino tmp.js
+  if [[ $? -eq 0 ]]; then echo pass rhino $file >> .test-log
+  else                    echo fail rhino $file >> .test-log
+                          echo -e "\033[1;31mfail rhino\033[0;0m: $file"; fi
+  rm -f tmp.js
 done
 
 grep '^fail' .test-log && $0 clean
